# Generated by Django 5.1.6 on 2025-02-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity_kg', models.FloatField()),
                ('speed_kmh', models.FloatField()),
                ('fuel_consumption_lh', models.FloatField()),
                ('operation_type', models.CharField(choices=[('harvest', 'Colheita'), ('transport', 'Transporte')], max_length=50)),
            ],
        ),
    ]
