# Generated by Django 5.1.6 on 2025-02-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.AddField(
            model_name='location',
            name='is_depot',
            field=models.BooleanField(default=False),
        ),
    ]
